#!/bin/bash

function usage {
	cat <<EOF
Usage $0 COMMAND [options]

Options:
	--help, -h                 Show this usage information
	--verbose, -v              Increase verbosity of ansible-playbook
	--module, -m <module>      Specific a module

Commands:
	list                       List all modules
	deploy                     Deploy elk
	destroy                    Destroy elk
EOF
}

EXTRA_OPTS=${EXTRA_OPTS}

while [ "$#" -gt 0 ]; do
case "$1" in
	(--verbose|-v)
		EXTRA_OPTS="$EXTRA_OPTS --verbose"
		shift 1
		;;
	(--help|-h)
		usage
		shift
		exit 0
		;;
	(--module|-m)
		EXTRA_OPTS="$EXTRA_OPTS --tags=$2"
		shift 2
		;;
	(*)
		break
		;;
esac
done

case "$1" in
(list)
    echo "elasticsearch | zookeeper | kafka | logstash | kibana"
    exit 0
	;;
(destroy)
	ACTION="Destroy elk containers"
	EXTAR_OPTS="$EXTRA_OPTS -e cmd=destroy"
	;;
(deploy)
	ACTION="Start elk containers"
	EXTAR_OPTS="$EXTRA_OPTS -e cmd=deploy"
	;;
(*) 
	usage
	exit 0
	;;
esac

echo $ACTION
ansible-playbook -i inventory/hosts site.yaml $EXTAR_OPTS

